"""
Test script demonstrating dynamic question generation for Part 1

To use Ollama (FREE - RECOMMENDED):
    1. Download Ollama from https://ollama.ai
    2. In one terminal: ollama serve
    3. In another terminal: ollama run mistral
    4. Run this script: python test_dynamic_questions.py

To use OpenAI/Anthropic APIs:
    export OPENAI_API_KEY="sk-..."        # For OpenAI
    export ANTHROPIC_API_KEY="sk-ant-..."  # For Anthropic
    python test_dynamic_questions.py
"""

import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.core.part1_questions import Part1QuestionEngine


def test_dynamic_generation():
    """Test the Part 1 question engine with dynamic generation"""
    
    print("=" * 70)
    print("🧪 TOEIC Part 1 - Dynamic Question Generation Test")
    print("=" * 70)
    print()
    
    # Test different levels
    levels = ["beginner", "intermediate", "advanced"]
    
    for level in levels:
        print(f"\n📚 Testing {level.upper()} level")
        print("-" * 70)
        
        # Initialize engine with LLM enabled
        engine = Part1QuestionEngine(level=level, use_llm=True)
        
        print(f"Generation source: {engine.get_generation_source()}")
        print()
        
        # Generate 2 questions per level as example
        for i in range(2):
            question = engine.generate_question()
            
            print(f"\nQuestion {i+1}:")
            print(f"  ID: {question['id']}")
            print(f"  Generated by: {question['generated_by']}")
            print(f"  Topic: {question['topic']}")
            print(f"  Difficulty: {question['difficulty']}")
            print(f"  Text: {question['text']}")
            print()


def test_fallback_generation():
    """Test fallback to hardcoded questions when no API key is set"""
    
    print("\n" + "=" * 70)
    print("🧪 Testing Fallback Generation (Hardcoded Mode)")
    print("=" * 70)
    print()
    
    # Disable LLM by removing API keys
    original_openai = os.environ.get("OPENAI_API_KEY")
    original_anthropic = os.environ.get("ANTHROPIC_API_KEY")
    
    if "OPENAI_API_KEY" in os.environ:
        del os.environ["OPENAI_API_KEY"]
    if "ANTHROPIC_API_KEY" in os.environ:
        del os.environ["ANTHROPIC_API_KEY"]
    
    try:
        # Initialize engine without LLM
        engine = Part1QuestionEngine(level="beginner", use_llm=True)
        
        print(f"Generation source: {engine.get_generation_source()}")
        print()
        
        # Generate a question
        question = engine.generate_question()
        
        print(f"Question:")
        print(f"  ID: {question['id']}")
        print(f"  Generated by: {question['generated_by']}")
        print(f"  Topic: {question['topic']}")
        print(f"  Difficulty: {question['difficulty']}")
        print(f"  Text: {question['text']}")
        
    finally:
        # Restore environment variables
        if original_openai:
            os.environ["OPENAI_API_KEY"] = original_openai
        if original_anthropic:
            os.environ["ANTHROPIC_API_KEY"] = original_anthropic


def test_sequence_generation():
    """Test generating a full sequence of 6 questions"""
    
    print("\n" + "=" * 70)
    print("🧪 Testing Full Sequence Generation (6 Questions)")
    print("=" * 70)
    print()
    
    engine = Part1QuestionEngine(level="intermediate", use_llm=True)
    
    print(f"Generation source: {engine.get_generation_source()}")
    print("Generating 6 questions for a complete Part 1 practice session...\n")
    
    questions = engine.get_part1_sequence(num_questions=6)
    
    for i, question in enumerate(questions, 1):
        print(f"\nQuestion {i}:")
        print(f"  Generated by: {question['generated_by']}")
        print(f"  Topic: {question['topic']}")
        print(f"  Difficulty: {question['difficulty']}")
        print(f"  Text: {question['text'][:60]}..." if len(question['text']) > 60 else f"  Text: {question['text']}")


if __name__ == "__main__":
    print("\n💡 Before running tests, make sure you have set your API key:")
    print("   • For OpenAI: set OPENAI_API_KEY environment variable")
    print("   • For Anthropic: set ANTHROPIC_API_KEY environment variable")
    print()
    
    # Run tests
    test_dynamic_generation()
    test_fallback_generation()
    test_sequence_generation()
    
    print("\n" + "=" * 70)
    print("✓ Tests completed!")
    print("=" * 70)
